### ISSUE TITLE
DiskNetCloneApp: Create a separate GitHub repository for the project

### ISSUE THREAD

**Issue by pkorotkov** [i-efremova/diploma#2]
Create a repo and migrate the current code base to it.

**Comment by i-efremova** [comment]
Created new repositories for 
-libchan proj: https://github.com/i-efremova/diskCloneLibchan
-custom_tcp proj: https://github.com/i-efremova/diskCloneCustomTCP
Also added repo with tests: https://github.com/i-efremova/diskCloneTests
